### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 8.00 GiB total capacity; 4.47 GiB alrea

### ISSUE THREAD

**Issue by c1a1o1** [afruehstueck/insetGAN#1]
RuntimeError: CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 8.00 GiB total capacity; 4.47 GiB alrea

**Comment by afruehstueck** [comment]
Which GPU are you attempting to run the code with? We recommend a GPU with at least 12GB of memory to accommodate the models.

**Comment by c1a1o1** [comment]
3080

**Comment by afruehstueck** [comment]
A 3080 shouldn't have issues memory-wise. This is speculative, but if the process previously crashed, some memory may still be retained from zombie python processes. Have you checked `nvidia-smi`?

**Comment by 123dddwn** [comment]
I have a same question. RuntimeError: CUDA out of memory. Tried to allocate 772.00 MiB (GPU 0; 4.00 GiB total capacity; 2.75 GiB already allocated;

> 3080

Did you fix this ?
