### ISSUE TITLE
Hello, may I ask if you could share the engineering file of using FID to evaluate images？

### ISSUE THREAD

**Issue by 1zhixiaoxiong** [afruehstueck/insetGAN#11]
Hello, may I ask if you could share the engineering file of using FID to evaluate images

**Comment by afruehstueck** [comment]
I usually rely on [pytorch-fid](https://github.com/mseitzer/pytorch-fid) for FID computation. It's fast and robust.

**Comment by 1zhixiaoxiong** [comment]
> 

Thank you very much!
