### ISSUE TITLE
No module named 'torch_utils.persistence'

### ISSUE THREAD

**Issue by quicksandznzn** [afruehstueck/insetGAN#12]
absl-py                 0.15.0
astunparse              1.6.3
cachetools              5.3.0
certifi                 2022.12.7
charset-normalizer      3.1.0
cloudpickle             2.2.1
colorama                0.4.6
cycler                  0.11.0
dask                    2022.2.0
dnnlib                  0.0.1
facenet-pytorch         2.5.2
ffmpeg-python           0.1.17
flatbuffers             1.12
fonttools               4.38.0
fsspec                  2023.1.0
future                  0.18.3
gast                    0.3.3
google-auth             2.17.3
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.32.0
h5py                    2.10.0
idna                    3.4
importlib-metadata      6.6.0
Keras-Preprocessing     1.1.2
kiwisolver              1.4.4
locket                  1.0.0
lpips                   0.1.4
Markdown                3.4.3
MarkupSafe              2.1.2
matplotlib              3.5.3
networkx                2.6.3
numexpr                 2.8.4
numpy                   1.21.6
oauthlib                3.2.2
onnx                    1.14.0
opt-einsum              3.3.0
packaging               23.1
partd                   1.4.0
Pillow                  9.5.0
pip                     22.3.1
protobuf                3.20.3
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pyparsing               3.0.9
PyQt5                   5.15.9
PyQt5-Qt5               5.15.2
PyQt5-sip               12.12.1
python-dateutil         2.8.2
PyWavelets              1.4.0
PyYAML                  6.0
requests                2.30.0
requests-oauthlib       1.3.1
rsa                     4.9
scikit-image            0.14.2
scipy                   1.4.1
setuptools              65.6.3
six                     1.15.0
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
termcolor               1.1.0
tf2onnx                 1.9.3
toolz                   0.12.0
torch                   1.10.0
torch-utils             0.1.2
torchaudio              0.10.0
torchvision             0.11.1
tqdm                    4.65.0
typing-extensions       3.7.4.3
urllib3                 2.0.2
Werkzeug                2.2.3
wheel                   0.38.4
wrapt                   1.12.1
zipp                    3.15.0

python run_insetgan.py

Traceback (most recent call last):
  File "run_insetgan.py", line 40, in <module>
    networks = pickle.Unpickler(f).load()
ModuleNotFoundError: No module named 'torch_utils.persistence'

**Comment by afruehstueck** [comment]
I believe this is a common problem when loading StyleGAN pkl files.
Please check the last reply in the following thread and see if it helps: https://github.com/rosinality/stylegan2-pytorch/issues/250#issuecomment-1547011789
