### ISSUE TITLE
some questions about env

### ISSUE THREAD

**Issue by 123dddwn** [afruehstueck/insetGAN#14]
Can the version of torch and cuda  be higher than the required version? And although higher versions need to be specified? Could you give some examples of torch and cuda versions?
Thank you!

**Comment by afruehstueck** [comment]
This combination of torch and cuda should work. 
`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=10.2 -c pytorch`
I am not sure about compatibility with newer versions, you would have to try that.
