### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by 123dddwn** [afruehstueck/insetGAN#16]
code:
with open('./networks/DeepFashion_1024x768.pkl', 'rb') as f:
    data = pickle.load(f)
dir_path = data['training_set_kwargs']['path']

Where is this path - '/tmp/fruehsa/data/FashionHumans.zip' ? Which folder should I go to ?
Thank you!

**Comment by afruehstueck** [comment]
Obviously the checkpoint saved a reference to the original training data directory that I trained this checkpoint on. I am not sure what you need it for?
We don't provide the dataset, only the trained checkpoint, but you can recreate the dataset from the DeepFashion data.
