### ISSUE TITLE
insetGAN for headtransfer (deepfake)

### ISSUE THREAD

**Issue by Deepak2405** [afruehstueck/insetGAN#6]
Can I use insetGAN for headtransfer? That is, take the head and neck part of user1 and seamlessly fit it on the body of user 2?

**Comment by afruehstueck** [comment]
Yes, you can do that. The easiest way is to generate random sets of heads and bodies and swap. If you wish to do a swap on existing people, you can leverage existing latent space inversion techniques like [e4e](https://github.com/omertov/encoder4editing) to find the appropriate face latent. We do not provide code for inversion of the body, but you could implement it analogously to existing optimization-based techniques.

**Comment by EJShim** [comment]
so, do I have to optimize face and body generators everytime (using run_insetGAN) for a single face swap image? 
or, is it possible to train generators to generate seamless face and body images?

**Comment by afruehstueck** [comment]
For the insetGAN method, you have to run the optimization pipeline for every seamless output.
