### ISSUE TITLE
Training data for canvas generator

### ISSUE THREAD

**Issue by zfkarl** [afruehstueck/insetGAN#8]
Can you illustrate for the provided pre-trained canvas generator model， which subset of deepfashion dataset is used for training?

**Comment by afruehstueck** [comment]
We run an OpenPose model on all the images contained in the DeepFashion dataset and select those that contain a full body. We evaluate this based on the confidence of the OpenPose keypoints - we want images with a high confidence of facial keypoints and also (at least one of) the ankle keypoints. Through this process we eliminate a substantial number of unsuitable images from DeepFashion which are either only showing the subject hip-upwards or which cut off the face (as is done for quite a few images showing only the upper body to model shirts)
